### ISSUE TITLE
\absoluteimage

### ISSUE THREAD

**Issue by briatte** [sprungknoedl/hk-template#1]
Dear @sprungknoedl 

I have been using [a 'lite' version](https://github.com/briatte/srqm/blob/master/course/slides/beamerthemehkllite.sty) of your theme for many years.

However, in the past few years, I have been getting an additional margin on the side of `\absoluteimage` slides, which I did not when I started using the theme years ago.

This bit of code:

```tex
  \begin{frame}[c, plain]{}
    \absoluteimage{\includegraphics[width=\paperwidth]{caravaggio}}
  \end{frame} 
```

currently returns this, instead of a 'full-slide, no-margin' image:

![screen shot 2017-10-01 at 07 08 40](https://user-images.githubusercontent.com/322533/31051967-65b61a40-a677-11e7-9ccc-a0b4fc5164ad.png)

I have not modified the `\absoluteimage` command that you designed.

I understand this package is orphaned, but just in case you might have an idea of what is going on, I'd be very thankful!

**Comment by sprungknoedl** [comment]
Hi François,

Sorry for the delay. I'm very surprised anyone is still using this package
(and ever used it outside my university).

I'm sorry but I don't think that I can help you. Last time I used LaTeX was
around 2013/2014, since then I do not even have it installed anymore.
Really sorry :(

Cheers,
Thomas

2017-10-01 7:09 GMT+02:00 François Briatte <notifications@github.com>:

**Comment by briatte** [comment]
No worries, thanks for your answer!
